-- ============================================================
-- Hive Music - Notifiche: NON APPLICARE questo file
-- ============================================================
-- Il sistema notifiche usa un approccio leggero basato su query
-- diretta (reviews + followers) senza tabella notifications,
-- trigger, stored procedure o event scheduler.
--
-- L'endpoint GET ?action=notifications in api.php recupera
-- le recensioni degli utenti seguiti nelle ultime 24h tramite
-- una semplice JOIN — nessuna infrastruttura DB aggiuntiva.
--
-- Questo file è mantenuto solo come riferimento storico.
-- ============================================================
